import fs from "node:fs";
import path from "node:path";
import { evidencePrefix, sideLabel, truncateChars, type Lang, type Side } from "@debate/shared";
import { PREVIOUS_DRAFT_MARKER } from "../prompts.js";
import type { AgentAdapter, AgentInvocation, AgentResult, MockHints } from "./types.js";

/** Build a deterministic 32-bit hash from a string (for the mock's branching). */
function hash32(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

function pick<T>(arr: T[], seed: number): T {
  return arr[seed % arr.length];
}

const ANGLES: Record<Lang, Record<Side, string[]>> = {
  ja: {
    affirmative: ["社会的コストの削減", "当事者の選択肢の拡大", "制度の持続可能性", "国際的な整合性", "技術による代替可能性", "先行事例の成功"],
    negative: ["移行コストの過小評価", "副作用と新たな格差", "現行制度の改善余地", "先行事例の失敗", "実施可能性の欠如", "価値の毀損"],
  },
  en: {
    affirmative: ["reducing social cost", "expanding stakeholders' options", "institutional sustainability", "international consistency", "substitutability via technology", "success of precedents"],
    negative: ["underestimated transition cost", "side effects and new inequality", "room to improve the current system", "failure of precedents", "lack of feasibility", "erosion of values"],
  },
};

function anglesOf(side: Side, lang: Lang): string[] {
  return ANGLES[lang][side];
}

function langOf(h: MockHints): Lang {
  return h.lang ?? "ja";
}

function mockEvidence(topic: string, side: Side, lang: Lang): object[] {
  const p = evidencePrefix(side);
  const angles = anglesOf(side, lang);
  return angles.map((angle, i) => ({
    id: `${p}-${String(i + 1).padStart(2, "0")}`,
    claim:
      lang === "en"
        ? `Grounds regarding "${topic}", from the angle of ${angle}, ${side === "affirmative" ? "supporting adoption" : "opposing adoption"}`
        : `「${topic}」に関して、${angle}の観点から${side === "affirmative" ? "実施を支持" : "実施に反対"}する根拠となる`,
    quote:
      lang === "en"
        ? `According to a mock survey, a statistically significant trend was confirmed regarding ${angle}, concluding that adopting the policy ${side === "affirmative" ? "yields a net benefit" : "yields a net loss"}. (This is mock evidence for smoke testing.)`
        : `モック調査によれば、${angle}について統計的に有意な傾向が確認されており、${side === "affirmative" ? "政策の実施は正味の便益をもたらす" : "政策の実施は正味の損失をもたらす"}と結論づけられている。（これは動作確認用のモック証拠です）`,
    source: {
      title: lang === "en" ? `Survey report on ${angle}` : `${angle}に関する調査報告書`,
      url: `https://example.com/mock/${p.toLowerCase()}${i + 1}`,
      publisher: lang === "en" ? "Mock Research Institute" : "モック総合研究所",
      publishedAt: "2025-04-01",
    },
    accessedAt: new Date().toISOString(),
  }));
}

function mockHandoutMd(topic: string, side: Side, lang: Lang): string {
  const p = evidencePrefix(side);
  const label = sideLabel(side, lang);
  const angles = anglesOf(side, lang);
  if (lang === "en") {
    const points = angles.map((a, i) => `- **${a}** ... evidence [${p}-${String(i + 1).padStart(2, "0")}]`).join("\n");
    return [
      `# Handout (${label})`,
      ``,
      `## Resolution`,
      `"${topic}"`,
      ``,
      `## Side`,
      `As the ${label}, we ${side === "affirmative" ? "support adopting this resolution" : "oppose adopting this resolution"}.`,
      ``,
      `## Argument structure`,
      points,
      ``,
      `## Note`,
      `This material was generated by the mock agent for smoke testing.`,
      ``,
    ].join("\n");
  }
  const points = angles.map((a, i) => `- **${a}** … 証拠 [${p}-${String(i + 1).padStart(2, "0")}]`).join("\n");
  return [
    `# ハンドアウト（${label}）`,
    ``,
    `## 論題`,
    `「${topic}」`,
    ``,
    `## 立場`,
    `${label}として、${side === "affirmative" ? "本論題の実施を支持する" : "本論題の実施に反対する"}。`,
    ``,
    `## 論点構成`,
    points,
    ``,
    `## 注記`,
    `この資料は動作確認用のモックエージェントが生成したものです。`,
    ``,
  ].join("\n");
}

function cite(p: string, n: number): string {
  return `[${p}-${String(n).padStart(2, "0")}]`;
}

function mockConstructive(h: MockHints): string {
  const lang = langOf(h);
  const side = h.side ?? "affirmative";
  const p = evidencePrefix(side);
  const angles = anglesOf(side, lang);
  const label = sideLabel(side, lang);
  if (lang === "en") {
    const kind = side === "affirmative" ? "advantage" : "disadvantage";
    return [
      `We present the ${label} constructive. On the resolution "${h.topic}", we offer two ${kind}s.`,
      ``,
      `The first ${kind} is "${angles[0]}". As ${cite(p, 1)} shows, a clear trend is confirmed in this area. If the status quo is left as is, ${side === "affirmative" ? "this benefit keeps being lost" : "this loss does not occur, but adopting the policy makes it materialize immediately"}. The mechanism is clear, and the institutional analysis in ${cite(p, 3)} backs it up.`,
      ``,
      `The second ${kind} is "${angles[1]}". Per ${cite(p, 2)}, the impact on stakeholders is statistically significant. In terms of severity too, the impact is broad and irreversible, so its significance is high.`,
      ``,
      `Therefore this ${kind} satisfies inherency, mechanism, and significance. That concludes the ${label} constructive.`,
    ].join("\n");
  }
  const label2 = side === "affirmative" ? "メリット" : "デメリット";
  return [
    `${label}の立論を行います。論題「${h.topic}」について、私たちは${label2}を二点提示します。`,
    ``,
    `第一の${label2}は「${angles[0]}」です。${cite(p, 1)}が示すとおり、この領域では明確な傾向が確認されています。現状を放置した場合${side === "affirmative" ? "この便益は失われ続けます" : "この損失は生じませんが、実施すれば直ちに顕在化します"}。発生過程は明確であり、${cite(p, 3)}の制度分析がこれを裏づけます。`,
    ``,
    `第二の${label2}は「${angles[1]}」です。${cite(p, 2)}によれば、当事者への影響は統計的に有意です。深刻性の観点でも、影響は広範かつ不可逆であり、重要性は高いと言えます。`,
    ``,
    `以上より、${label2}は固有性・発生過程・重要性のいずれも満たしています。${label}としての立論を終わります。`,
  ].join("\n");
}

function mockRebuttal(h: MockHints, seed: number): string {
  const lang = langOf(h);
  const side = h.side ?? "affirmative";
  const p = evidencePrefix(side);
  const op = evidencePrefix(side === "affirmative" ? "negative" : "affirmative");
  const angles = anglesOf(side, lang);
  const oppAngles = anglesOf(side === "affirmative" ? "negative" : "affirmative", lang);
  const label = sideLabel(side, lang);
  if (lang === "en") {
    const extra = h.part?.id === "2NR" ? ` Moreover, new data ${cite(p, 99)} reinforces this point.` : "";
    return [
      `We present our rebuttal.`,
      ``,
      `First, against the opponent's claim about "${pick(oppAngles, seed)}". Their evidence ${cite(op, (seed % 3) + 1)} was surveyed at an old time and does not reflect the current situation. The trend shown by our ${cite(p, (seed % 4) + 1)} better fits the present.${extra}`,
      ``,
      `Next, the comparison. Even if the opponent's point holds, its impact is limited and recoverable. Our "${angles[seed % 2]}", by contrast, is broad and irreversible. Given the scale of ${cite(p, 2)}, it is clear the ${label} prevails on weighing.`,
      ``,
      `For these reasons, this match should be voted for the ${label}.`,
    ].join("\n");
  }
  const extra = h.part?.id === "2NR" ? ` さらに新データ${cite(p, 99)}もこの点を補強します。` : "";
  return [
    `反駁を行います。`,
    ``,
    `まず相手の主張する「${pick(oppAngles, seed)}」への反論です。相手の証拠 ${cite(op, (seed % 3) + 1)} は調査時点が古く、直近の状況を反映していません。私たちの ${cite(p, (seed % 4) + 1)} が示す傾向のほうが現状に即しています。${extra}`,
    ``,
    `次に比較です。相手の論点が仮に成立しても、その影響は限定的かつ回復可能です。一方、私たちの示した「${angles[seed % 2]}」は広範で不可逆です。${cite(p, 2)}の規模感を踏まえれば、比較衡量で${label}が優位であることは明らかです。`,
    ``,
    `以上の理由から、本試合は${label}に投票されるべきです。`,
  ].join("\n");
}

function mockQuestion(h: MockHints, seed: number): string {
  const lang = langOf(h);
  const op = evidencePrefix(h.side === "affirmative" ? "negative" : "affirmative");
  if (lang === "en") {
    const targets = [
      `Does the survey scope of evidence ${cite(op, (seed % 3) + 1)} match this resolution's scope of application? Please show your grounds.`,
      `For your ${(seed % 2) + 1}${(seed % 2) + 1 === 1 ? "st" : "nd"} point, which evidence backs the causal chain of the mechanism?`,
      `Over what period after adoption do you expect the stated impact to materialize? On what grounds?`,
      `Why can't the opponent's assumed alternative achieve the same effect?`,
    ];
    return pick(targets, seed);
  }
  const targets = [
    `証拠 ${cite(op, (seed % 3) + 1)} の調査対象は本論題の適用範囲と一致していますか。一致する根拠を示してください。`,
    `第${(seed % 2) + 1}の論点について、発生過程の因果関係はどの証拠で裏づけられますか。`,
    `提示された影響の規模は、実施後どの程度の期間で顕在化すると想定していますか。その根拠は何ですか。`,
    `相手側の想定する代替手段では、なぜ同じ効果が得られないのですか。`,
  ];
  return pick(targets, seed);
}

function mockAnswer(h: MockHints, seed: number): string {
  const lang = langOf(h);
  const p = evidencePrefix(h.side ?? "affirmative");
  if (lang === "en") {
    const answers = [
      `Yes. The survey in ${cite(p, (seed % 3) + 1)} was conducted in the same institutional environment as this resolution, so the scope matches.`,
      `The mechanism is laid out step by step in the institutional analysis of ${cite(p, (seed % 4) + 1)}. There is no leap in causation.`,
      `We expect the impact to materialize within a few years of adoption. The precedent in ${cite(p, 2)} shows a similar time course.`,
      `The alternative has a limited scope and cannot achieve the scale of effect shown by ${cite(p, 1)}.`,
    ];
    return pick(answers, seed);
  }
  const answers = [
    `はい。${cite(p, (seed % 3) + 1)} の調査は本論題の対象と同一の制度環境で行われており、適用範囲は一致します。`,
    `発生過程は ${cite(p, (seed % 4) + 1)} の制度分析が段階を追って示しています。因果の飛躍はありません。`,
    `影響は実施後おおむね数年で顕在化すると考えます。${cite(p, 2)} の先行事例が同様の時間経過を示しています。`,
    `代替手段では対象範囲が限定され、${cite(p, 1)} の示す規模の効果は得られません。`,
  ];
  return pick(answers, seed);
}

function mockJudgeJson(h: MockHints, seed: number): string {
  const lang = langOf(h);
  const vote: Side = seed % 100 < 50 ? "affirmative" : "negative";
  const winner = sideLabel(vote, lang);
  const loser = sideLabel(vote === "affirmative" ? "negative" : "affirmative", lang);
  const affId = (h.evidenceIds ?? ["A-01"])[0] ?? "A-01";
  const negId = (h.opponentEvidenceIds ?? ["N-01"])[0] ?? "N-01";
  const verdict =
    lang === "en"
      ? {
          vote,
          decisiveIssues: [
            `The ${winner}'s first point survived rebuttal to the end, while the ${loser}'s main point drew doubt on the scope of its grounds during cross-examination`,
            `On the weighing, the ${winner} more clearly showed the scale and irreversibility of the impact`,
          ],
          speechEvaluations: [
            { partId: "1AC", comment: "Clear argument structure and appropriate evidence-ID linking" },
            { partId: "1NC", comment: "Good counter-axis, but some claims sit at a distance from the evidence" },
            { partId: "2NR", comment: "Referenced a nonexistent evidence ID; penalized on staying within the material" },
            { partId: "2AR", comment: "The comparison summary was clear, but part of it drifted toward a near-new argument" },
          ],
          evidenceAssessment: [
            { evidenceId: affId, reliability: "medium", comment: "Source is stated but single-sourced, so weakly corroborated" },
            { evidenceId: negId, reliability: "medium", comment: "The survey timing is somewhat old" },
          ],
          violations:
            seed % 2 === 0
              ? [{ type: "unknown-evidence", partId: "2NR", detail: "Reference to an evidence ID not in the sealed material" }]
              : [],
          communication: {
            clarity: "Both teams labeled well and organized their points clearly",
            responsiveness: `The ${winner} responded more directly to the opponent's speeches`,
            comment: "Cross-examination engaged reasonably well",
          },
          reasoning: `After weighing advantages and disadvantages, the ${winner}'s main point survived more and its impact was more severe, so I vote for the ${winner}. (Auto-generated by the mock judge.)`,
        }
      : {
          vote,
          decisiveIssues: [
            `${winner}の第一論点が反駁を耐えて最後まで残った一方、${loser}の主要論点は質疑で根拠の適用範囲に疑義が生じた`,
            `比較衡量の局面で${winner}のほうが影響の規模と不可逆性を明確に示した`,
          ],
          speechEvaluations: [
            { partId: "1AC", comment: "論点構成は明確で証拠 ID の紐づけも適切" },
            { partId: "1NC", comment: "対抗軸の提示は良いが、一部の主張で証拠との距離がある" },
            { partId: "2NR", comment: "存在しない証拠 ID への言及があり、資料に閉じる原則の点で減点" },
            { partId: "2AR", comment: "比較のまとめは分かりやすいが、新規論点に近い展開が一部見られた" },
          ],
          evidenceAssessment: [
            { evidenceId: affId, reliability: "中", comment: "出典は明示されているが単一ソースで裏取りが薄い" },
            { evidenceId: negId, reliability: "中", comment: "調査時点がやや古い" },
          ],
          violations:
            seed % 2 === 0
              ? [{ type: "unknown-evidence", partId: "2NR", detail: "封印資料に存在しない証拠 ID の参照" }]
              : [],
          communication: {
            clarity: "両チームともラベル付けが明確で論点整理は良好",
            responsiveness: `${winner}のほうが相手発言への直接の応答が多かった`,
            comment: "質疑の噛み合いはおおむね良好だった",
          },
          reasoning: `メリットとデメリットの比較衡量の結果、${winner}の主要論点の残存度と影響の重大性が上回ると判断し、${winner}に投票する。（モック審査員による自動生成）`,
        };
  return JSON.stringify(verdict);
}

function mockReviewJson(h: MockHints): string {
  const lang = langOf(h);
  const review =
    lang === "en"
      ? {
          decisiveIssues: [`The comparison of impact scale on "${h.topic ?? "the resolution"}" became the final battleground, and the difference in handling during the second rebuttal decided the match`],
          turningPoints: ["In the negative's first rebuttal the attack on the affirmative's first point was thin, and the affirmative's argument locked in here"],
          strongEvidence: [{ evidenceId: "A-01", comment: "Referenced consistently from the constructive to the final rebuttal and never rebutted" }],
          weakEvidence: [{ evidenceId: "N-02", comment: "Its scope was pressed during cross-examination and never recovered in later rebuttals" }],
          effectiveRebuttals: ["The evidence-timing comparison in the affirmative's first rebuttal effectively cut the opponent's evidence reliability"],
          suspectedOutOfHandout: ["The [N-99] in the negative's second rebuttal is not in the sealed material and is suspected to be outside the handout"],
          judgeDifferences: "The judges split on the weighting of the comparison. Those who weighted irreversibility voted affirmative; those who weighted probability of occurrence voted negative.",
          preparationComparison: "Both teams had 6 pieces of evidence, so quantity was equal. The affirmative's points mapped one-to-one to evidence clearly, while the negative reused the same evidence across multiple points at times.",
          teamOperationComparison: "The council team had much overlap between drafts and lost on statement density. The role-division team had the edge in cross-examination engagement. (Mock commentary)",
          improvements: {
            A: ["Re-cite evidence more in the rebuttal parts to show judges the argument stays within the material"],
            B: ["Avoid referencing nonexistent evidence IDs. Do a final check of the evidence list during preparation"],
          },
        }
      : {
          decisiveIssues: [`「${h.topic ?? "論題"}」の影響規模の比較が最終盤の争点となり、第二反駁での処理の差が勝敗を分けた`],
          turningPoints: ["否定側第一反駁で肯定側の第一論点への攻撃が薄く、ここで肯定側の議論が固定化した"],
          strongEvidence: [{ evidenceId: "A-01", comment: "立論から最終反駁まで一貫して参照され、反論を受けなかった" }],
          weakEvidence: [{ evidenceId: "N-02", comment: "質疑で適用範囲を突かれ、以降の反駁で回復できなかった" }],
          effectiveRebuttals: ["肯定側第一反駁での証拠の時点比較は、相手証拠の信頼性を効果的に削った"],
          suspectedOutOfHandout: ["否定側第二反駁の [N-99] は封印資料に存在せず、ハンドアウト外の疑いがある"],
          judgeDifferences: "審査員の判断は比較衡量の重み付けで分かれた。影響の不可逆性を重く見た審査員は肯定側、発生確率を重く見た審査員は否定側に投票した。",
          preparationComparison: "両チームとも証拠6件で量は同等。肯定側は論点と証拠の対応が一対一で明確、否定側は複数論点で同じ証拠を使い回す場面があった。",
          teamOperationComparison: "合議制チームは草案間の重複が多く statement の密度で損をした。役割分担制チームは質疑の噛み合いで優位だった。（モック解説）",
          improvements: {
            A: ["反駁パートでの証拠の再引用を増やし、資料に閉じた議論であることを審査員に示す"],
            B: ["存在しない証拠 ID への言及を避ける。準備フェーズで証拠一覧の最終確認を行う"],
          },
        };
  return JSON.stringify(review);
}

export class MockAdapter implements AgentAdapter {
  readonly provider = "mock";

  async invoke(inv: AgentInvocation): Promise<AgentResult> {
    const started = Date.now();
    const h = inv.mockHints ?? {};
    const lang = langOf(h);
    const seed = hash32(`${inv.matchId}:${inv.agent.id}:${inv.kind}:${h.part?.id ?? ""}:${h.exchangeIndex ?? 0}`);
    // Wait a little so progress is visible in the spectator UI.
    await sleep(250 + (seed % 400));

    const topic = h.topic ?? (lang === "en" ? "the resolution" : "論題");
    let output = "";
    switch (inv.kind) {
      case "prep-research":
        output =
          lang === "en"
            ? [
                `# Research notes (${inv.agent.name})`,
                `- Organized ${sideLabel(h.side ?? "affirmative", lang)} candidate points for the resolution "${topic}"`,
                `- Promising angles: ${anglesOf(h.side ?? "affirmative", lang).slice(0, 3).join(" / ")}`,
                `- Opponent's likely claims: ${anglesOf(h.side === "negative" ? "affirmative" : "negative", lang).slice(0, 2).join(" / ")}`,
                `- Source candidates: various survey reports from the Mock Research Institute`,
              ].join("\n")
            : [
                `# 調査メモ（${inv.agent.name}）`,
                `- 論題「${topic}」について${sideLabel(h.side ?? "affirmative", lang)}視点の論点候補を整理`,
                `- 有望な角度: ${anglesOf(h.side ?? "affirmative", lang).slice(0, 3).join(" / ")}`,
                `- 相手の想定主張: ${anglesOf(h.side === "negative" ? "affirmative" : "negative", lang).slice(0, 2).join(" / ")}`,
                `- 出典候補: モック総合研究所の各種調査報告`,
              ].join("\n");
        break;
      case "prep-compile":
      case "prep-fix": {
        const side = h.side ?? "affirmative";
        fs.writeFileSync(
          path.join(inv.workspaceDir, "evidence.json"),
          JSON.stringify(mockEvidence(topic, side, lang), null, 2),
          "utf8",
        );
        fs.writeFileSync(path.join(inv.workspaceDir, "handout.md"), mockHandoutMd(topic, side, lang), "utf8");
        const p = evidencePrefix(side);
        const ids = Array.from({ length: 6 }, (_, i) => `${p}-${String(i + 1).padStart(2, "0")}`).join(", ");
        output = lang === "en" ? `Created: ${ids}` : `作成済み: ${ids}`;
        break;
      }
      case "speech":
      case "draft":
        output = h.part?.kind === "constructive" ? mockConstructive(h) : mockRebuttal(h, seed);
        if (inv.kind === "draft") output += lang === "en" ? `\n(${inv.agent.name}'s draft)` : `\n（${inv.agent.name} の草案）`;
        break;
      case "merge": {
        // The drafts are in the instructions, but the mock just adds a note to its own generation.
        const base = h.part?.kind === "constructive" ? mockConstructive(h) : mockRebuttal(h, seed);
        output = base + (lang === "en" ? `\n(Final version after team deliberation)` : `\n（チーム合議を経た最終版）`);
        break;
      }
      case "question":
        output = mockQuestion(h, seed + (h.exchangeIndex ?? 0));
        break;
      case "answer":
        output = mockAnswer(h, seed + (h.exchangeIndex ?? 0));
        break;
      case "regenerate":
        output = truncateChars(inv.instructions.split(PREVIOUS_DRAFT_MARKER)[1] ?? "", (h.maxChars ?? 400) - 10).trim();
        break;
      case "judge":
        await sleep(500);
        output = mockJudgeJson(h, seed);
        break;
      case "review":
        await sleep(500);
        output = mockReviewJson(h);
        break;
    }

    return { output, toolUsage: [], durationMs: Date.now() - started };
  }
}
